### ISSUE TITLE
ISRES constructor lacks population parameter

### ISSUE THREAD

**Issue by tkx68** [peddie/hmatrix-nlopt#1]
The ISRES algorithm uses a population parameter in NLOPT but unfortunately it is not there in hmatrix-nlopt in the ISRES constructor. It would be very nice if it could be added.

**Comment by peddie** [comment]
I apologize for the hilarious delay in replying; somehow github did not notify me about this issue.

This shouldn't be hard to add.  In what version of `nlopt` did this parameter appear?

**Comment by peddie** [comment]
Please see version 0.2.0.0, [now on Hackage](https://hackage.haskell.org/package/hmatrix-nlopt-0.2.0.0/docs/Numeric-NLOPT.html#t:GlobalAlgorithm).
